# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeePort' do
    pod 'Alamofire'
    pod "MagicalRecord"
    pod 'SDWebImage'
use_frameworks!

# Pods for CoffeePort

target 'CoffeePortTests' do
inherit! :search_paths
# Pods for testing
end

end
