# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeePort' do
    pod 'Alamofire'
    pod 'MagicalRecord', '~> 2.3.0'
    pod 'SDWebImage'
    pod 'DGActivityIndicatorView'
    pod 'ReachabilitySwift'
    pod 'Nocilla'
use_frameworks!

# Pods for CoffeePort

target 'CoffeePortTests' do
inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod  'Mockingjay'
end

end
